[package]
name = "smashbing-web"
version = "0.1.0"
authors = ["Nathaniel Knight <nknight@cfenet.ubc.ca>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
libsmashbing = {path = "../libsmashbing"}