build:
    cargo build --target wasm32-unknown-unknown

bind: build
    wasm-bindgen target/wasm32-unknown-unknown/debug/smashbing_web.wasm --out-dir . --no-modules

get-tools:
    rustup target add wasm32-unknown-unknown --toolchain nightly
    cargo install --force wasm-bindgen-cli

clean:
    rm -f *.js *.ts *.wasm
    cargo clean
