[package]
name = "libsmashbing"
version = "0.1.0"
authors = ["Nat Knight <nathaniel.ep@gmail.com>"]

[dependencies]

[dependencies.rand]
git = "https://github.com/rust-random/rand"
version = "0.6.0-pre.0"
features = ["wasm-bindgen"]